#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""evaluate.py - quality report for the detector: per class and per brightness.

Two modes:
  * labelled  - YOLO labels are present (dataset generated by synth_dataset.py, or
                your own licensed dataset): precision / recall / F1 per class at
                IoU >= 0.5, split by image brightness;
  * unlabelled - no labels: detection statistics only (how many images trigger,
                score distribution, brightness buckets).

Examples:
  python tools/evaluate.py --images dataset/images/val --names dataset/dataset.yaml
  python tools/evaluate.py --images dataset/images/val --multi --json report.json
  python tools/evaluate.py --images dataset/images/val --no-multi   # single pass vs multi
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from nsfw_guard.core import ALL_CLASSES, Detector  # noqa: E402

IMAGE_EXT = (".jpg", ".jpeg", ".png", ".bmp", ".webp")
BUCKETS = [(0.0, 0.25, "dark   (<0.25)"),
           (0.25, 0.5, "dim    (0.25-0.5)"),
           (0.5, 0.75, "normal (0.5-0.75)"),
           (0.75, 1.01, "bright (>0.75)")]


def iou(a, b) -> float:
    ax, ay, aw, ah = [float(v) for v in a]
    bx, by, bw, bh = [float(v) for v in b]
    x1, y1 = max(ax, bx), max(ay, by)
    x2, y2 = min(ax + aw, bx + bw), min(ay + ah, by + bh)
    inter = max(0.0, x2 - x1) * max(0.0, y2 - y1)
    union = aw * ah + bw * bh - inter
    return inter / union if union > 0 else 0.0


def read_names(path: str):
    """Parse the `names:` list from a YOLO dataset.yaml (inline or block form)."""
    if not path or not os.path.isfile(path):
        return None
    try:
        text = open(path, "r", encoding="utf-8").read()
    except Exception:
        return None
    lines = [line.rstrip("\n") for line in text.splitlines()]
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("names:"):
            continue
        tail = stripped.split(":", 1)[1].strip()
        if tail.startswith("["):
            return [part.strip().strip("'\"") for part in tail.strip("[]").split(",") if part.strip()]
        names = []
        for follow in lines[index + 1:]:
            if not follow.startswith((" ", "\t", "-")):
                break
            item = follow.strip().lstrip("-").strip()
            if ":" in item:
                item = item.split(":", 1)[1].strip()
            names.append(item.strip("'\""))
        return names or None
    return None


def load_labels(path: str, width: int, height: int):
    """YOLO labels -> [[x, y, w, h, class_index], ...] in pixels."""
    boxes = []
    if not path or not os.path.isfile(path):
        return boxes
    for line in open(path, "r", encoding="utf-8"):
        parts = line.split()
        if len(parts) < 5:
            continue
        try:
            cls, cx, cy, bw, bh = (float(parts[0]), float(parts[1]),
                                   float(parts[2]), float(parts[3]), float(parts[4]))
        except ValueError:
            continue
        boxes.append([(cx - bw / 2) * width, (cy - bh / 2) * height,
                      bw * width, bh * height, int(cls)])
    return boxes


def bucket_of(luma: float):
    for low, high, name in BUCKETS:
        if low <= luma < high:
            return name
    return BUCKETS[-1][2]


def luma_of(image) -> float:
    import cv2
    return float(cv2.cvtColor(image, cv2.COLOR_BGR2GRAY).mean()) / 255.0

def auto_label_path(image_path: str, images_root: str) -> str:
    """YOLO layout: <root>/images/<split>/x.jpg -> <root>/labels/<split>/x.txt"""
    parts = os.path.normpath(image_path).split(os.sep)
    if "images" not in parts:
        return ""
    index = len(parts) - 1 - parts[::-1].index("images")
    candidate = os.sep.join(parts[:index] + ["labels"] + parts[index + 1:])
    candidate = os.path.splitext(candidate)[0] + ".txt"
    return candidate if os.path.exists(candidate) else ""


def evaluate(args) -> dict:
    import cv2
    from collections import defaultdict

    files = []
    for ext in IMAGE_EXT:
        files += glob.glob(os.path.join(args.images, "**", "*" + ext), recursive=True)
    files = sorted(set(files))
    if not files:
        raise SystemExit("no images found in %s" % args.images)

    names = read_names(args.names) if args.names else None
    detector = Detector(threshold=args.threshold, explicit=list(ALL_CLASSES))
    per_class = defaultdict(lambda: [0, 0, 0])          # tp, fp, fn
    per_bucket = defaultdict(lambda: {"images": 0, "triggered": 0, "tp": 0, "fp": 0, "fn": 0, "ms": 0})
    summary = {"images": 0, "triggered": 0, "detections": 0, "ms": 0, "labelled": bool(names),
               "multi": bool(args.multi), "threshold": args.threshold}

    for path in files:
        image = cv2.imread(path, cv2.IMREAD_COLOR)
        if image is None:
            continue
        height, width = image.shape[:2]
        result = detector.analyse(image, multi=args.multi)
        bucket = bucket_of(luma_of(image))
        slot = per_bucket[bucket]

        label_path = os.path.splitext(path)[0] + ".txt"
        if args.labels:
            label_path = os.path.join(args.labels, os.path.basename(os.path.splitext(path)[0]) + ".txt")
        elif not os.path.exists(label_path):
            label_path = auto_label_path(path, args.images)
        ground_truth = load_labels(label_path, width, height) if names else []

        dets = [d for d in result["detections"] if float(d["score"]) >= args.threshold]
        summary["images"] += 1
        summary["ms"] += int(result.get("ms", 0))
        summary["detections"] += len(dets)
        slot["images"] += 1
        slot["ms"] += int(result.get("ms", 0))
        if result["verdict"]:
            summary["triggered"] += 1
            slot["triggered"] += 1

        if not names:
            continue

        used = set()
        for det in dets:
            best, best_iou = None, 0.0
            for index, box in enumerate(ground_truth):
                if index in used:
                    continue
                if box[4] < len(names) and names[box[4]] != det["class"]:
                    continue
                value = iou(det["box"], box[:4])
                if value > best_iou:
                    best, best_iou = index, value
            if best is not None and best_iou >= 0.5:
                used.add(best)
                per_class[det["class"]][0] += 1
                slot["tp"] += 1
            else:
                per_class[det["class"]][1] += 1
                slot["fp"] += 1
        for index, box in enumerate(ground_truth):
            if index in used:
                continue
            name = names[box[4]] if box[4] < len(names) else str(box[4])
            per_class[name][2] += 1
            slot["fn"] += 1

    return {"summary": summary, "per_class": dict(per_class), "per_bucket": dict(per_bucket),
            "files": len(files), "source": args.images}


def render(report: dict) -> str:
    summary = report["summary"]
    lines = []
    lines.append("images: %d  detections: %d  triggered: %d  avg %.0f ms  passes: %s  threshold: %.2f" % (
        summary["images"], summary["detections"], summary["triggered"],
        summary["ms"] / max(1, summary["images"]), "multi" if summary["multi"] else "single",
        summary["threshold"]))
    lines.append("")
    lines.append("brightness bucket        images  triggered  TP  FP  FN   recall  precision")
    for _low, _high, name in BUCKETS:
        slot = report["per_bucket"].get(name)
        if not slot:
            continue
        recall = slot["tp"] / max(1, slot["tp"] + slot["fn"])
        precision = slot["tp"] / max(1, slot["tp"] + slot["fp"])
        lines.append("%-22s %6d %10d %3d %3d %3d   %6.2f  %9.2f" % (
            name, slot["images"], slot["triggered"], slot["tp"], slot["fp"], slot["fn"],
            recall, precision))
    if report["per_class"]:
        lines.append("")
        lines.append("class                            TP  FP  FN   recall  precision     F1")
        for name in sorted(report["per_class"]):
            tp, fp, fn = report["per_class"][name]
            recall = tp / max(1, tp + fn)
            precision = tp / max(1, tp + fp)
            f1 = 2 * precision * recall / max(1e-9, precision + recall)
            lines.append("%-30s %3d %3d %3d   %6.2f  %9.2f  %5.2f" % (name, tp, fp, fn, recall, precision, f1))
    else:
        lines.append("")
        lines.append("no labels found - only detection statistics above (pass --names dataset.yaml)")
    return "\n".join(lines)


def build_parser():
    parser = argparse.ArgumentParser(description="nsfw-guard quality report")
    parser.add_argument("--images", required=True, help="folder with images")
    parser.add_argument("--labels", help="folder with YOLO .txt labels (default: next to images)")
    parser.add_argument("--names", help="dataset.yaml with the class names")
    parser.add_argument("--threshold", type=float, default=0.35)
    parser.add_argument("--no-multi", dest="multi", action="store_false", default=True,
                        help="single exposure instead of multi")
    parser.add_argument("--json", help="write the raw report to this file")
    return parser


def main(argv=None) -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    args = build_parser().parse_args(argv)
    started = time.time()
    report = evaluate(args)
    print(render(report))
    print("\ntotal %.1fs" % (time.time() - started))
    if args.json:
        with open(args.json, "w", encoding="utf-8") as handle:
            json.dump(report, handle, ensure_ascii=False, indent=2)
        print("report written to %s" % args.json)
    return 0


if __name__ == "__main__":
    sys.exit(main())
